apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookingmicroservice
  name: booking-service
spec:
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    app: bookingmicroservice
  type: LoadBalancer
status:
  loadBalancer: {}
